services:
  - type: web
    name: gym-backend
    runtime: docker
    dockerfilePath: ./gym-backend/Dockerfile
    dockerContext: ./gym-backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
